[2023-04-29T15:44:35.190-0300] {processor.py:153} INFO - Started process (PID=21754) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:44:35.191-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T15:44:35.192-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:44:35.192-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:44:35.194-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:44:35.193-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T15:44:35.195-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:44:35.210-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.021 seconds
[2023-04-29T15:45:25.583-0300] {processor.py:153} INFO - Started process (PID=21878) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:45:25.590-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T15:45:25.591-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:45:25.591-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:45:25.593-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:45:25.592-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T15:45:25.594-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:45:25.605-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.024 seconds
[2023-04-29T15:46:08.681-0300] {processor.py:153} INFO - Started process (PID=21934) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:46:08.687-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T15:46:08.688-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:46:08.688-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:46:08.690-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:46:08.689-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T15:46:08.691-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:46:08.701-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.022 seconds
[2023-04-29T15:46:39.944-0300] {processor.py:153} INFO - Started process (PID=21997) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:46:39.945-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T15:46:39.945-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:46:39.945-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:46:39.947-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:46:39.946-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T15:46:39.948-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:46:39.958-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.016 seconds
[2023-04-29T15:47:12.686-0300] {processor.py:153} INFO - Started process (PID=22038) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:47:12.687-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T15:47:12.688-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:47:12.688-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:47:12.690-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:47:12.688-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T15:47:12.690-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:47:12.700-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.016 seconds
[2023-04-29T15:47:45.809-0300] {processor.py:153} INFO - Started process (PID=22090) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:47:45.816-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T15:47:45.817-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:47:45.817-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:47:45.819-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:47:45.818-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T15:47:45.819-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:47:45.831-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.024 seconds
[2023-04-29T15:48:18.786-0300] {processor.py:153} INFO - Started process (PID=22168) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:48:18.793-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T15:48:18.794-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:48:18.794-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:48:18.797-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:48:18.795-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T15:48:18.797-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:48:18.807-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.022 seconds
[2023-04-29T15:48:53.568-0300] {processor.py:153} INFO - Started process (PID=22237) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:48:53.569-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T15:48:53.570-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:48:53.570-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:48:53.573-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:48:53.571-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T15:48:53.574-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:48:53.587-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.020 seconds
[2023-04-29T15:49:25.523-0300] {processor.py:153} INFO - Started process (PID=22276) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:49:25.530-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T15:49:25.530-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:49:25.530-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:49:25.533-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:49:25.531-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T15:49:25.533-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:49:25.545-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.025 seconds
[2023-04-29T15:50:12.262-0300] {processor.py:153} INFO - Started process (PID=22394) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:50:12.269-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T15:50:12.269-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:50:12.269-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:50:12.272-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:50:12.271-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T15:50:12.272-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:50:12.286-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.025 seconds
[2023-04-29T15:50:48.789-0300] {processor.py:153} INFO - Started process (PID=22492) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:50:48.796-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T15:50:48.797-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:50:48.797-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:50:48.799-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:50:48.798-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T15:50:48.800-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:50:48.811-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.023 seconds
[2023-04-29T15:51:20.610-0300] {processor.py:153} INFO - Started process (PID=22534) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:51:20.617-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T15:51:20.618-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:51:20.618-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:51:20.620-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:51:20.619-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T15:51:20.620-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:51:20.631-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.024 seconds
[2023-04-29T15:51:51.602-0300] {processor.py:153} INFO - Started process (PID=22565) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:51:51.609-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T15:51:51.610-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:51:51.610-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:51:51.612-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:51:51.611-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T15:51:51.612-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:51:51.623-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.023 seconds
[2023-04-29T15:52:35.696-0300] {processor.py:153} INFO - Started process (PID=22624) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:52:35.703-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T15:52:35.705-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:52:35.704-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:52:35.707-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:52:35.706-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T15:52:35.707-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:52:35.719-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.025 seconds
[2023-04-29T15:53:06.794-0300] {processor.py:153} INFO - Started process (PID=22658) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:53:06.801-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T15:53:06.802-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:53:06.801-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:53:06.805-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:53:06.803-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T15:53:06.806-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:53:06.816-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.025 seconds
[2023-04-29T15:53:41.058-0300] {processor.py:153} INFO - Started process (PID=22711) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:53:41.059-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T15:53:41.059-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:53:41.059-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:53:41.061-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:53:41.060-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T15:53:41.062-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:53:41.076-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.020 seconds
[2023-04-29T15:54:12.070-0300] {processor.py:153} INFO - Started process (PID=22756) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:54:12.077-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T15:54:12.078-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:54:12.078-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:54:12.080-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:54:12.079-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T15:54:12.081-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:54:12.091-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.023 seconds
[2023-04-29T15:54:54.633-0300] {processor.py:153} INFO - Started process (PID=22820) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:54:54.640-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T15:54:54.640-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:54:54.640-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:54:54.642-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:54:54.641-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T15:54:54.643-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:54:54.655-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.023 seconds
[2023-04-29T15:55:26.251-0300] {processor.py:153} INFO - Started process (PID=22858) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:55:26.258-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T15:55:26.258-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:55:26.258-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:55:26.260-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:55:26.259-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T15:55:26.261-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:55:26.272-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.023 seconds
[2023-04-29T15:55:58.691-0300] {processor.py:153} INFO - Started process (PID=22905) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:55:58.694-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T15:55:58.695-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:55:58.695-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:55:58.697-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:55:58.696-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T15:55:58.697-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:55:58.709-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.019 seconds
[2023-04-29T15:56:42.693-0300] {processor.py:153} INFO - Started process (PID=22977) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:56:42.700-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T15:56:42.701-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:56:42.701-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:56:42.703-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:56:42.702-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T15:56:42.703-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:56:42.723-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.032 seconds
[2023-04-29T15:57:13.217-0300] {processor.py:153} INFO - Started process (PID=23026) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:57:13.224-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T15:57:13.224-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:57:13.224-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:57:13.226-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:57:13.225-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T15:57:13.227-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:57:13.239-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.024 seconds
[2023-04-29T15:57:54.069-0300] {processor.py:153} INFO - Started process (PID=23075) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:57:54.076-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T15:57:54.077-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:57:54.077-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:57:54.079-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:57:54.078-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T15:57:54.080-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:57:54.091-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.024 seconds
[2023-04-29T15:58:37.114-0300] {processor.py:153} INFO - Started process (PID=23166) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:58:37.121-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T15:58:37.121-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:58:37.121-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:58:37.124-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:58:37.122-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T15:58:37.124-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:58:37.136-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.024 seconds
[2023-04-29T15:59:07.739-0300] {processor.py:153} INFO - Started process (PID=23207) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:59:07.746-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T15:59:07.747-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:59:07.746-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:59:07.749-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:59:07.748-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T15:59:07.750-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:59:07.760-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.023 seconds
[2023-04-29T15:59:39.344-0300] {processor.py:153} INFO - Started process (PID=23295) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:59:39.351-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T15:59:39.352-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:59:39.351-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:59:39.354-0300] {logging_mixin.py:137} INFO - [2023-04-29T15:59:39.353-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T15:59:39.354-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T15:59:39.364-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.023 seconds
[2023-04-29T16:00:23.869-0300] {processor.py:153} INFO - Started process (PID=23444) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:00:23.876-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T16:00:23.877-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:00:23.877-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:00:23.879-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:00:23.879-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T16:00:23.880-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:00:23.890-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.023 seconds
[2023-04-29T16:00:56.754-0300] {processor.py:153} INFO - Started process (PID=23481) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:00:56.755-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T16:00:56.756-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:00:56.756-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:00:56.758-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:00:56.757-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T16:00:56.758-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:00:56.769-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.016 seconds
[2023-04-29T16:01:27.712-0300] {processor.py:153} INFO - Started process (PID=23518) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:01:27.713-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T16:01:27.713-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:01:27.713-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:01:27.715-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:01:27.714-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T16:01:27.716-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:01:27.727-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.017 seconds
[2023-04-29T16:02:01.031-0300] {processor.py:153} INFO - Started process (PID=23551) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:02:01.031-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T16:02:01.032-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:02:01.032-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:02:01.034-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:02:01.033-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T16:02:01.034-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:02:01.045-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.016 seconds
[2023-04-29T16:02:32.788-0300] {processor.py:153} INFO - Started process (PID=23587) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:02:32.795-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T16:02:32.796-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:02:32.796-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:02:32.798-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:02:32.797-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T16:02:32.799-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:02:32.809-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.023 seconds
[2023-04-29T16:03:15.988-0300] {processor.py:153} INFO - Started process (PID=23667) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:03:15.995-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T16:03:15.996-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:03:15.996-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:03:15.998-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:03:15.997-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T16:03:15.998-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:03:16.012-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.028 seconds
[2023-04-29T16:03:49.272-0300] {processor.py:153} INFO - Started process (PID=23707) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:03:49.279-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T16:03:49.280-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:03:49.280-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:03:49.282-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:03:49.281-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T16:03:49.283-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:03:49.293-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.023 seconds
[2023-04-29T16:04:34.247-0300] {processor.py:153} INFO - Started process (PID=23762) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:04:34.254-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T16:04:34.255-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:04:34.255-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:04:34.257-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:04:34.257-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T16:04:34.258-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:04:34.269-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.024 seconds
[2023-04-29T16:05:09.182-0300] {processor.py:153} INFO - Started process (PID=23806) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:05:09.189-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T16:05:09.190-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:05:09.190-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:05:09.193-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:05:09.192-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T16:05:09.193-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:05:09.204-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.024 seconds
[2023-04-29T16:05:41.546-0300] {processor.py:153} INFO - Started process (PID=23842) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:05:41.554-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T16:05:41.554-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:05:41.554-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:05:41.556-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:05:41.555-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T16:05:41.557-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:05:41.568-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.024 seconds
[2023-04-29T16:06:12.410-0300] {processor.py:153} INFO - Started process (PID=23879) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:06:12.417-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T16:06:12.418-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:06:12.418-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:06:12.420-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:06:12.419-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T16:06:12.421-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:06:12.433-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.024 seconds
[2023-04-29T16:06:45.769-0300] {processor.py:153} INFO - Started process (PID=23912) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:06:45.776-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T16:06:45.778-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:06:45.778-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:06:45.779-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:06:45.778-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T16:06:45.780-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:06:45.791-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.024 seconds
[2023-04-29T16:07:17.787-0300] {processor.py:153} INFO - Started process (PID=23955) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:07:17.793-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T16:07:17.795-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:07:17.794-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:07:17.797-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:07:17.796-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T16:07:17.797-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:07:17.808-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.024 seconds
[2023-04-29T16:07:49.242-0300] {processor.py:153} INFO - Started process (PID=24189) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:07:49.243-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T16:07:49.244-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:07:49.243-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:07:49.245-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:07:49.244-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T16:07:49.246-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:07:49.257-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.017 seconds
[2023-04-29T16:08:29.866-0300] {processor.py:153} INFO - Started process (PID=24277) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:08:29.867-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T16:08:29.867-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:08:29.867-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:08:29.869-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:08:29.868-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T16:08:29.870-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:08:29.881-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.017 seconds
[2023-04-29T16:09:03.816-0300] {processor.py:153} INFO - Started process (PID=24317) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:09:03.823-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T16:09:03.824-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:09:03.824-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:09:03.826-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:09:03.825-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T16:09:03.826-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:09:03.838-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.024 seconds
[2023-04-29T16:09:34.755-0300] {processor.py:153} INFO - Started process (PID=24354) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:09:34.762-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T16:09:34.763-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:09:34.763-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:09:34.765-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:09:34.764-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T16:09:34.765-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:09:34.776-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.023 seconds
[2023-04-29T16:10:05.734-0300] {processor.py:153} INFO - Started process (PID=24396) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:10:05.741-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T16:10:05.742-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:10:05.742-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:10:05.744-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:10:05.743-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T16:10:05.744-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:10:05.755-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.023 seconds
[2023-04-29T16:10:49.900-0300] {processor.py:153} INFO - Started process (PID=24446) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:10:49.907-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T16:10:49.908-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:10:49.908-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:10:49.910-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:10:49.909-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T16:10:49.910-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:10:49.923-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.026 seconds
[2023-04-29T16:11:20.431-0300] {processor.py:153} INFO - Started process (PID=24485) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:11:20.438-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T16:11:20.438-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:11:20.438-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:11:20.441-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:11:20.439-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T16:11:20.442-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:11:20.452-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.024 seconds
[2023-04-29T16:11:51.851-0300] {processor.py:153} INFO - Started process (PID=24528) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:11:51.852-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T16:11:51.852-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:11:51.852-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:11:51.854-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:11:51.853-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T16:11:51.854-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:11:51.865-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.016 seconds
[2023-04-29T16:12:26.434-0300] {processor.py:153} INFO - Started process (PID=24810) to work on /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:12:26.441-0300] {processor.py:743} INFO - Processing file /home/nicholas10/airflow/dags/debug.py for tasks to queue
[2023-04-29T16:12:26.442-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:12:26.442-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:12:26.444-0300] {logging_mixin.py:137} INFO - [2023-04-29T16:12:26.443-0300] {dagbag.py:341} ERROR - Failed to import: /home/nicholas10/airflow/dags/debug.py
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas10/airflow/dags/debug.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2023-04-29T16:12:26.444-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/nicholas10/airflow/dags/debug.py
[2023-04-29T16:12:26.455-0300] {processor.py:175} INFO - Processing /home/nicholas10/airflow/dags/debug.py took 0.023 seconds
