[2023-04-29T15:35:36.841-0300] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: climate_dag.extract_data scheduled__2023-04-17T00:00:00+00:00 [queued]>
[2023-04-29T15:35:36.847-0300] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: climate_dag.extract_data scheduled__2023-04-17T00:00:00+00:00 [queued]>
[2023-04-29T15:35:36.847-0300] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-29T15:35:36.847-0300] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-04-29T15:35:36.847-0300] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-29T15:35:36.856-0300] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): extract_data> on 2023-04-17 00:00:00+00:00
[2023-04-29T15:35:36.860-0300] {standard_task_runner.py:55} INFO - Started process 20787 to run task
[2023-04-29T15:35:36.863-0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'climate_dag', 'extract_data', 'scheduled__2023-04-17T00:00:00+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/climate_data.py', '--cfg-path', '/tmp/tmp8w6mm7hg']
[2023-04-29T15:35:36.864-0300] {standard_task_runner.py:83} INFO - Job 78: Subtask extract_data
[2023-04-29T15:35:36.895-0300] {task_command.py:388} INFO - Running <TaskInstance: climate_dag.extract_data scheduled__2023-04-17T00:00:00+00:00 [running]> on host nicholas10-ThinkPad-E14-Gen-3
[2023-04-29T15:35:36.912-0300] {abstractoperator.py:611} ERROR - Exception rendering Jinja template for task 'extract_data', field 'op_kwargs'. Template: {'data_interval_end': '{{data_interval_end.strftime(%Y-%m-%d)}}'}
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 603, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 678, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 678, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 661, in render_template
    template = jinja_env.from_string(value)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
[2023-04-29T15:35:36.913-0300] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1377, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1495, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2122, in render_templates
    original_task.render_template_fields(context)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1179, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 603, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 678, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 678, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 661, in render_template
    template = jinja_env.from_string(value)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
[2023-04-29T15:35:36.916-0300] {taskinstance.py:1321} INFO - Marking task as FAILED. dag_id=climate_dag, task_id=extract_data, execution_date=20230417T000000, start_date=20230429T183536, end_date=20230429T183536
[2023-04-29T15:35:36.924-0300] {standard_task_runner.py:100} ERROR - Failed to execute job 78 for task extract_data (unexpected '%'; 20787)
[2023-04-29T15:35:36.954-0300] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-29T15:35:36.962-0300] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-04-29T15:39:39.399-0300] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: climate_dag.extract_data scheduled__2023-04-17T00:00:00+00:00 [queued]>
[2023-04-29T15:39:39.405-0300] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: climate_dag.extract_data scheduled__2023-04-17T00:00:00+00:00 [queued]>
[2023-04-29T15:39:39.405-0300] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-29T15:39:39.405-0300] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-04-29T15:39:39.405-0300] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-29T15:39:39.414-0300] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): extract_data> on 2023-04-17 00:00:00+00:00
[2023-04-29T15:39:39.419-0300] {standard_task_runner.py:55} INFO - Started process 21318 to run task
[2023-04-29T15:39:39.421-0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'climate_dag', 'extract_data', 'scheduled__2023-04-17T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/climate_data.py', '--cfg-path', '/tmp/tmpi5nvvplr']
[2023-04-29T15:39:39.422-0300] {standard_task_runner.py:83} INFO - Job 16: Subtask extract_data
[2023-04-29T15:39:39.453-0300] {task_command.py:388} INFO - Running <TaskInstance: climate_dag.extract_data scheduled__2023-04-17T00:00:00+00:00 [running]> on host nicholas10-ThinkPad-E14-Gen-3
[2023-04-29T15:39:39.471-0300] {abstractoperator.py:611} ERROR - Exception rendering Jinja template for task 'extract_data', field 'op_kwargs'. Template: {'data_interval_end': '{{data_interval_end.strftime(%Y-%m-%d)}}'}
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 603, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 678, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 678, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 661, in render_template
    template = jinja_env.from_string(value)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
[2023-04-29T15:39:39.472-0300] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1377, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1495, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2122, in render_templates
    original_task.render_template_fields(context)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1179, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 603, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 678, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 678, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 661, in render_template
    template = jinja_env.from_string(value)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
[2023-04-29T15:39:39.474-0300] {taskinstance.py:1321} INFO - Marking task as FAILED. dag_id=climate_dag, task_id=extract_data, execution_date=20230417T000000, start_date=20230429T183939, end_date=20230429T183939
[2023-04-29T15:39:39.482-0300] {standard_task_runner.py:100} ERROR - Failed to execute job 16 for task extract_data (unexpected '%'; 21318)
[2023-04-29T15:39:39.513-0300] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-29T15:39:39.522-0300] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-04-29T15:45:23.769-0300] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: climate_dag.extract_data scheduled__2023-04-17T00:00:00+00:00 [queued]>
[2023-04-29T15:45:23.774-0300] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: climate_dag.extract_data scheduled__2023-04-17T00:00:00+00:00 [queued]>
[2023-04-29T15:45:23.774-0300] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-29T15:45:23.774-0300] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-04-29T15:45:23.774-0300] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-29T15:45:23.783-0300] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): extract_data> on 2023-04-17 00:00:00+00:00
[2023-04-29T15:45:23.786-0300] {standard_task_runner.py:55} INFO - Started process 21876 to run task
[2023-04-29T15:45:23.788-0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'climate_dag', 'extract_data', 'scheduled__2023-04-17T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/climate_data.py', '--cfg-path', '/tmp/tmpil0fi1b1']
[2023-04-29T15:45:23.789-0300] {standard_task_runner.py:83} INFO - Job 16: Subtask extract_data
[2023-04-29T15:45:23.819-0300] {task_command.py:388} INFO - Running <TaskInstance: climate_dag.extract_data scheduled__2023-04-17T00:00:00+00:00 [running]> on host nicholas10-ThinkPad-E14-Gen-3
[2023-04-29T15:45:23.834-0300] {abstractoperator.py:611} ERROR - Exception rendering Jinja template for task 'extract_data', field 'op_kwargs'. Template: {'data_interval_end': '{{data_interval_end.strftime(%Y-%m-%d)}}'}
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 603, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 678, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 678, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 661, in render_template
    template = jinja_env.from_string(value)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
[2023-04-29T15:45:23.835-0300] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1377, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1495, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2122, in render_templates
    original_task.render_template_fields(context)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1179, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 603, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 678, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 678, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 661, in render_template
    template = jinja_env.from_string(value)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
[2023-04-29T15:45:23.838-0300] {taskinstance.py:1321} INFO - Marking task as FAILED. dag_id=climate_dag, task_id=extract_data, execution_date=20230417T000000, start_date=20230429T184523, end_date=20230429T184523
[2023-04-29T15:45:23.845-0300] {standard_task_runner.py:100} ERROR - Failed to execute job 16 for task extract_data (unexpected '%'; 21876)
[2023-04-29T15:45:23.880-0300] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-29T15:45:23.888-0300] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-04-29T15:50:38.772-0300] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: climate_dag.extract_data scheduled__2023-04-17T00:00:00+00:00 [queued]>
[2023-04-29T15:50:38.778-0300] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: climate_dag.extract_data scheduled__2023-04-17T00:00:00+00:00 [queued]>
[2023-04-29T15:50:38.778-0300] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-29T15:50:38.779-0300] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-04-29T15:50:38.779-0300] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-29T15:50:38.787-0300] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): extract_data> on 2023-04-17 00:00:00+00:00
[2023-04-29T15:50:38.791-0300] {standard_task_runner.py:55} INFO - Started process 22480 to run task
[2023-04-29T15:50:38.794-0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'climate_dag', 'extract_data', 'scheduled__2023-04-17T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/climate_data.py', '--cfg-path', '/tmp/tmpvrv_wh9y']
[2023-04-29T15:50:38.795-0300] {standard_task_runner.py:83} INFO - Job 16: Subtask extract_data
[2023-04-29T15:50:38.827-0300] {task_command.py:388} INFO - Running <TaskInstance: climate_dag.extract_data scheduled__2023-04-17T00:00:00+00:00 [running]> on host nicholas10-ThinkPad-E14-Gen-3
[2023-04-29T15:50:38.863-0300] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=climate_dag
AIRFLOW_CTX_TASK_ID=extract_data
AIRFLOW_CTX_EXECUTION_DATE=2023-04-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-17T00:00:00+00:00
[2023-04-29T15:50:41.014-0300] {python.py:177} INFO - Done. Returned value was: None
[2023-04-29T15:50:41.021-0300] {taskinstance.py:1321} INFO - Marking task as SUCCESS. dag_id=climate_dag, task_id=extract_data, execution_date=20230417T000000, start_date=20230429T185038, end_date=20230429T185041
[2023-04-29T15:50:41.056-0300] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-04-29T15:50:41.064-0300] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
