[2023-04-29T15:35:26.670-0300] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: climate_dag.extract_data scheduled__2023-04-03T00:00:00+00:00 [queued]>
[2023-04-29T15:35:26.682-0300] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: climate_dag.extract_data scheduled__2023-04-03T00:00:00+00:00 [queued]>
[2023-04-29T15:35:26.682-0300] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-29T15:35:26.682-0300] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-04-29T15:35:26.682-0300] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-29T15:35:26.700-0300] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): extract_data> on 2023-04-03 00:00:00+00:00
[2023-04-29T15:35:26.707-0300] {standard_task_runner.py:55} INFO - Started process 20734 to run task
[2023-04-29T15:35:26.713-0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'climate_dag', 'extract_data', 'scheduled__2023-04-03T00:00:00+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/climate_data.py', '--cfg-path', '/tmp/tmpdiwcnesy']
[2023-04-29T15:35:26.715-0300] {standard_task_runner.py:83} INFO - Job 74: Subtask extract_data
[2023-04-29T15:35:26.771-0300] {task_command.py:388} INFO - Running <TaskInstance: climate_dag.extract_data scheduled__2023-04-03T00:00:00+00:00 [running]> on host nicholas10-ThinkPad-E14-Gen-3
[2023-04-29T15:35:26.795-0300] {abstractoperator.py:611} ERROR - Exception rendering Jinja template for task 'extract_data', field 'op_kwargs'. Template: {'data_interval_end': '{{data_interval_end.strftime(%Y-%m-%d)}}'}
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 603, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 678, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 678, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 661, in render_template
    template = jinja_env.from_string(value)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
[2023-04-29T15:35:26.797-0300] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1377, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1495, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2122, in render_templates
    original_task.render_template_fields(context)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1179, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 603, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 678, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 678, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 661, in render_template
    template = jinja_env.from_string(value)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
[2023-04-29T15:35:26.800-0300] {taskinstance.py:1321} INFO - Marking task as FAILED. dag_id=climate_dag, task_id=extract_data, execution_date=20230403T000000, start_date=20230429T183526, end_date=20230429T183526
[2023-04-29T15:35:26.810-0300] {standard_task_runner.py:100} ERROR - Failed to execute job 74 for task extract_data (unexpected '%'; 20734)
[2023-04-29T15:35:26.844-0300] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-29T15:35:26.854-0300] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-04-29T15:39:32.002-0300] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: climate_dag.extract_data scheduled__2023-04-03T00:00:00+00:00 [queued]>
[2023-04-29T15:39:32.006-0300] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: climate_dag.extract_data scheduled__2023-04-03T00:00:00+00:00 [queued]>
[2023-04-29T15:39:32.007-0300] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-29T15:39:32.007-0300] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-04-29T15:39:32.007-0300] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-29T15:39:32.015-0300] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): extract_data> on 2023-04-03 00:00:00+00:00
[2023-04-29T15:39:32.019-0300] {standard_task_runner.py:55} INFO - Started process 21286 to run task
[2023-04-29T15:39:32.021-0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'climate_dag', 'extract_data', 'scheduled__2023-04-03T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/climate_data.py', '--cfg-path', '/tmp/tmpgyrmxyc7']
[2023-04-29T15:39:32.022-0300] {standard_task_runner.py:83} INFO - Job 13: Subtask extract_data
[2023-04-29T15:39:32.054-0300] {task_command.py:388} INFO - Running <TaskInstance: climate_dag.extract_data scheduled__2023-04-03T00:00:00+00:00 [running]> on host nicholas10-ThinkPad-E14-Gen-3
[2023-04-29T15:39:32.071-0300] {abstractoperator.py:611} ERROR - Exception rendering Jinja template for task 'extract_data', field 'op_kwargs'. Template: {'data_interval_end': '{{data_interval_end.strftime(%Y-%m-%d)}}'}
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 603, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 678, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 678, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 661, in render_template
    template = jinja_env.from_string(value)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
[2023-04-29T15:39:32.071-0300] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1377, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1495, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2122, in render_templates
    original_task.render_template_fields(context)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1179, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 603, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 678, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 678, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 661, in render_template
    template = jinja_env.from_string(value)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
[2023-04-29T15:39:32.074-0300] {taskinstance.py:1321} INFO - Marking task as FAILED. dag_id=climate_dag, task_id=extract_data, execution_date=20230403T000000, start_date=20230429T183932, end_date=20230429T183932
[2023-04-29T15:39:32.082-0300] {standard_task_runner.py:100} ERROR - Failed to execute job 13 for task extract_data (unexpected '%'; 21286)
[2023-04-29T15:39:32.113-0300] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-29T15:39:32.122-0300] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-04-29T15:45:16.174-0300] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: climate_dag.extract_data scheduled__2023-04-03T00:00:00+00:00 [queued]>
[2023-04-29T15:45:16.180-0300] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: climate_dag.extract_data scheduled__2023-04-03T00:00:00+00:00 [queued]>
[2023-04-29T15:45:16.181-0300] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-29T15:45:16.181-0300] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-04-29T15:45:16.181-0300] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-29T15:45:16.189-0300] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): extract_data> on 2023-04-03 00:00:00+00:00
[2023-04-29T15:45:16.193-0300] {standard_task_runner.py:55} INFO - Started process 21844 to run task
[2023-04-29T15:45:16.196-0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'climate_dag', 'extract_data', 'scheduled__2023-04-03T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/climate_data.py', '--cfg-path', '/tmp/tmpufkqsevt']
[2023-04-29T15:45:16.197-0300] {standard_task_runner.py:83} INFO - Job 13: Subtask extract_data
[2023-04-29T15:45:16.229-0300] {task_command.py:388} INFO - Running <TaskInstance: climate_dag.extract_data scheduled__2023-04-03T00:00:00+00:00 [running]> on host nicholas10-ThinkPad-E14-Gen-3
[2023-04-29T15:45:16.245-0300] {abstractoperator.py:611} ERROR - Exception rendering Jinja template for task 'extract_data', field 'op_kwargs'. Template: {'data_interval_end': '{{data_interval_end.strftime(%Y-%m-%d)}}'}
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 603, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 678, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 678, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 661, in render_template
    template = jinja_env.from_string(value)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
[2023-04-29T15:45:16.246-0300] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1377, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1495, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2122, in render_templates
    original_task.render_template_fields(context)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1179, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 603, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 678, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 678, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 661, in render_template
    template = jinja_env.from_string(value)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
[2023-04-29T15:45:16.249-0300] {taskinstance.py:1321} INFO - Marking task as FAILED. dag_id=climate_dag, task_id=extract_data, execution_date=20230403T000000, start_date=20230429T184516, end_date=20230429T184516
[2023-04-29T15:45:16.256-0300] {standard_task_runner.py:100} ERROR - Failed to execute job 13 for task extract_data (unexpected '%'; 21844)
[2023-04-29T15:45:16.288-0300] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-29T15:45:16.297-0300] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-04-29T15:50:27.457-0300] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: climate_dag.extract_data scheduled__2023-04-03T00:00:00+00:00 [queued]>
[2023-04-29T15:50:27.463-0300] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: climate_dag.extract_data scheduled__2023-04-03T00:00:00+00:00 [queued]>
[2023-04-29T15:50:27.463-0300] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-29T15:50:27.463-0300] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-04-29T15:50:27.463-0300] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-29T15:50:27.472-0300] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): extract_data> on 2023-04-03 00:00:00+00:00
[2023-04-29T15:50:27.476-0300] {standard_task_runner.py:55} INFO - Started process 22447 to run task
[2023-04-29T15:50:27.479-0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'climate_dag', 'extract_data', 'scheduled__2023-04-03T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/climate_data.py', '--cfg-path', '/tmp/tmpwdx3tb9m']
[2023-04-29T15:50:27.480-0300] {standard_task_runner.py:83} INFO - Job 13: Subtask extract_data
[2023-04-29T15:50:27.511-0300] {task_command.py:388} INFO - Running <TaskInstance: climate_dag.extract_data scheduled__2023-04-03T00:00:00+00:00 [running]> on host nicholas10-ThinkPad-E14-Gen-3
[2023-04-29T15:50:27.546-0300] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=climate_dag
AIRFLOW_CTX_TASK_ID=extract_data
AIRFLOW_CTX_EXECUTION_DATE=2023-04-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-03T00:00:00+00:00
[2023-04-29T15:50:29.253-0300] {python.py:177} INFO - Done. Returned value was: None
[2023-04-29T15:50:29.256-0300] {taskinstance.py:1321} INFO - Marking task as SUCCESS. dag_id=climate_dag, task_id=extract_data, execution_date=20230403T000000, start_date=20230429T185027, end_date=20230429T185029
[2023-04-29T15:50:29.297-0300] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-04-29T15:50:29.305-0300] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
