[2023-04-29T15:35:34.397-0300] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: climate_dag.extract_data scheduled__2023-04-10T00:00:00+00:00 [queued]>
[2023-04-29T15:35:34.402-0300] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: climate_dag.extract_data scheduled__2023-04-10T00:00:00+00:00 [queued]>
[2023-04-29T15:35:34.402-0300] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-29T15:35:34.402-0300] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-04-29T15:35:34.402-0300] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-29T15:35:34.410-0300] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): extract_data> on 2023-04-10 00:00:00+00:00
[2023-04-29T15:35:34.413-0300] {standard_task_runner.py:55} INFO - Started process 20768 to run task
[2023-04-29T15:35:34.416-0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'climate_dag', 'extract_data', 'scheduled__2023-04-10T00:00:00+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/climate_data.py', '--cfg-path', '/tmp/tmpk6pc2glk']
[2023-04-29T15:35:34.417-0300] {standard_task_runner.py:83} INFO - Job 77: Subtask extract_data
[2023-04-29T15:35:34.445-0300] {task_command.py:388} INFO - Running <TaskInstance: climate_dag.extract_data scheduled__2023-04-10T00:00:00+00:00 [running]> on host nicholas10-ThinkPad-E14-Gen-3
[2023-04-29T15:35:34.465-0300] {abstractoperator.py:611} ERROR - Exception rendering Jinja template for task 'extract_data', field 'op_kwargs'. Template: {'data_interval_end': '{{data_interval_end.strftime(%Y-%m-%d)}}'}
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 603, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 678, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 678, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 661, in render_template
    template = jinja_env.from_string(value)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
[2023-04-29T15:35:34.467-0300] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1377, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1495, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2122, in render_templates
    original_task.render_template_fields(context)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1179, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 603, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 678, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 678, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 661, in render_template
    template = jinja_env.from_string(value)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
[2023-04-29T15:35:34.471-0300] {taskinstance.py:1321} INFO - Marking task as FAILED. dag_id=climate_dag, task_id=extract_data, execution_date=20230410T000000, start_date=20230429T183534, end_date=20230429T183534
[2023-04-29T15:35:34.479-0300] {standard_task_runner.py:100} ERROR - Failed to execute job 77 for task extract_data (unexpected '%'; 20768)
[2023-04-29T15:35:34.508-0300] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-29T15:35:34.516-0300] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-04-29T15:39:34.158-0300] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: climate_dag.extract_data scheduled__2023-04-10T00:00:00+00:00 [queued]>
[2023-04-29T15:39:34.163-0300] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: climate_dag.extract_data scheduled__2023-04-10T00:00:00+00:00 [queued]>
[2023-04-29T15:39:34.163-0300] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-29T15:39:34.164-0300] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-04-29T15:39:34.164-0300] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-29T15:39:34.173-0300] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): extract_data> on 2023-04-10 00:00:00+00:00
[2023-04-29T15:39:34.176-0300] {standard_task_runner.py:55} INFO - Started process 21296 to run task
[2023-04-29T15:39:34.179-0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'climate_dag', 'extract_data', 'scheduled__2023-04-10T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/climate_data.py', '--cfg-path', '/tmp/tmp4hnp7f6_']
[2023-04-29T15:39:34.180-0300] {standard_task_runner.py:83} INFO - Job 14: Subtask extract_data
[2023-04-29T15:39:34.211-0300] {task_command.py:388} INFO - Running <TaskInstance: climate_dag.extract_data scheduled__2023-04-10T00:00:00+00:00 [running]> on host nicholas10-ThinkPad-E14-Gen-3
[2023-04-29T15:39:34.227-0300] {abstractoperator.py:611} ERROR - Exception rendering Jinja template for task 'extract_data', field 'op_kwargs'. Template: {'data_interval_end': '{{data_interval_end.strftime(%Y-%m-%d)}}'}
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 603, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 678, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 678, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 661, in render_template
    template = jinja_env.from_string(value)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
[2023-04-29T15:39:34.228-0300] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1377, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1495, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2122, in render_templates
    original_task.render_template_fields(context)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1179, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 603, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 678, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 678, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 661, in render_template
    template = jinja_env.from_string(value)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
[2023-04-29T15:39:34.231-0300] {taskinstance.py:1321} INFO - Marking task as FAILED. dag_id=climate_dag, task_id=extract_data, execution_date=20230410T000000, start_date=20230429T183934, end_date=20230429T183934
[2023-04-29T15:39:34.239-0300] {standard_task_runner.py:100} ERROR - Failed to execute job 14 for task extract_data (unexpected '%'; 21296)
[2023-04-29T15:39:34.270-0300] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-29T15:39:34.278-0300] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-04-29T15:45:18.352-0300] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: climate_dag.extract_data scheduled__2023-04-10T00:00:00+00:00 [queued]>
[2023-04-29T15:45:18.356-0300] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: climate_dag.extract_data scheduled__2023-04-10T00:00:00+00:00 [queued]>
[2023-04-29T15:45:18.357-0300] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-29T15:45:18.357-0300] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-04-29T15:45:18.357-0300] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-29T15:45:18.366-0300] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): extract_data> on 2023-04-10 00:00:00+00:00
[2023-04-29T15:45:18.369-0300] {standard_task_runner.py:55} INFO - Started process 21854 to run task
[2023-04-29T15:45:18.372-0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'climate_dag', 'extract_data', 'scheduled__2023-04-10T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/climate_data.py', '--cfg-path', '/tmp/tmp9aboqnby']
[2023-04-29T15:45:18.373-0300] {standard_task_runner.py:83} INFO - Job 14: Subtask extract_data
[2023-04-29T15:45:18.405-0300] {task_command.py:388} INFO - Running <TaskInstance: climate_dag.extract_data scheduled__2023-04-10T00:00:00+00:00 [running]> on host nicholas10-ThinkPad-E14-Gen-3
[2023-04-29T15:45:18.422-0300] {abstractoperator.py:611} ERROR - Exception rendering Jinja template for task 'extract_data', field 'op_kwargs'. Template: {'data_interval_end': '{{data_interval_end.strftime(%Y-%m-%d)}}'}
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 603, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 678, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 678, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 661, in render_template
    template = jinja_env.from_string(value)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
[2023-04-29T15:45:18.422-0300] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1377, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1495, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2122, in render_templates
    original_task.render_template_fields(context)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1179, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 603, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 678, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 678, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 661, in render_template
    template = jinja_env.from_string(value)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/nicholas10/airflow/dataengvenv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
[2023-04-29T15:45:18.426-0300] {taskinstance.py:1321} INFO - Marking task as FAILED. dag_id=climate_dag, task_id=extract_data, execution_date=20230410T000000, start_date=20230429T184518, end_date=20230429T184518
[2023-04-29T15:45:18.434-0300] {standard_task_runner.py:100} ERROR - Failed to execute job 14 for task extract_data (unexpected '%'; 21854)
[2023-04-29T15:45:18.464-0300] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-29T15:45:18.472-0300] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-04-29T15:50:31.379-0300] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: climate_dag.extract_data scheduled__2023-04-10T00:00:00+00:00 [queued]>
[2023-04-29T15:50:31.384-0300] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: climate_dag.extract_data scheduled__2023-04-10T00:00:00+00:00 [queued]>
[2023-04-29T15:50:31.384-0300] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-29T15:50:31.384-0300] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-04-29T15:50:31.384-0300] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-29T15:50:31.393-0300] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): extract_data> on 2023-04-10 00:00:00+00:00
[2023-04-29T15:50:31.396-0300] {standard_task_runner.py:55} INFO - Started process 22457 to run task
[2023-04-29T15:50:31.399-0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'climate_dag', 'extract_data', 'scheduled__2023-04-10T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/climate_data.py', '--cfg-path', '/tmp/tmp7e7t6o71']
[2023-04-29T15:50:31.400-0300] {standard_task_runner.py:83} INFO - Job 14: Subtask extract_data
[2023-04-29T15:50:31.431-0300] {task_command.py:388} INFO - Running <TaskInstance: climate_dag.extract_data scheduled__2023-04-10T00:00:00+00:00 [running]> on host nicholas10-ThinkPad-E14-Gen-3
[2023-04-29T15:50:31.466-0300] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=climate_dag
AIRFLOW_CTX_TASK_ID=extract_data
AIRFLOW_CTX_EXECUTION_DATE=2023-04-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-10T00:00:00+00:00
[2023-04-29T15:50:33.646-0300] {python.py:177} INFO - Done. Returned value was: None
[2023-04-29T15:50:33.653-0300] {taskinstance.py:1321} INFO - Marking task as SUCCESS. dag_id=climate_dag, task_id=extract_data, execution_date=20230410T000000, start_date=20230429T185031, end_date=20230429T185033
[2023-04-29T15:50:33.699-0300] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-04-29T15:50:33.707-0300] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
